package frontline.combat.fcp.client.model.Aavp;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.entity.vehicle.Aavp.AAVPEntity;
import frontline.combat.fcp.entity.vehicle.Bmp.BMP1Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class AAVPModel extends VehicleModel<AAVPEntity> {

    @Override
    public ResourceLocation getModelResource(AAVPEntity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/aavp.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    // Generated by Track Builder - 50 tracks
    // Pivot: [0, 16.04, 50.24]

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {175.86f, 16.04f, 50.24f},
            {128.32f, 14.30f, 53.97f},
            {79.11f, 10.34f, 55.04f},
            {29.89f, 6.96f, 52.70f},
            {26.76f, 5.09f, 48.89f},
            {26.76f, 3.18f, 45.10f},
            {26.76f, 1.27f, 41.31f},
            {0.00f, 0.59f, 37.19f},
            {0.00f, 0.59f, 32.94f},
            {0.00f, 0.59f, 28.70f},
            {0.00f, 0.59f, 24.46f},
            {0.00f, 0.59f, 20.21f},
            {0.00f, 0.59f, 15.97f},
            {0.00f, 0.59f, 11.72f},
            {0.00f, 0.59f, 7.48f},
            {0.00f, 0.59f, 3.23f},
            {0.00f, 0.59f, -1.01f},
            {0.00f, 0.59f, -5.25f},
            {0.00f, 0.59f, -9.50f},
            {0.00f, 0.59f, -13.74f},
            {0.00f, 0.59f, -17.99f},
            {0.00f, 0.59f, -22.23f},
            {-0.59f, 0.59f, -26.48f},
            {-32.52f, 1.88f, -30.43f},
            {-31.58f, 4.10f, -34.05f},
            {-31.58f, 6.32f, -37.66f},
            {-45.03f, 8.70f, -41.16f},
            {-84.29f, 12.50f, -42.88f},
            {-123.56f, 16.56f, -41.95f},
            {-157.91f, 19.21f, -38.73f},
            {178.45f, 19.55f, -34.54f},
            {177.12f, 19.33f, -30.30f},
            {177.12f, 19.12f, -26.06f},
            {177.12f, 18.91f, -21.83f},
            {177.12f, 18.69f, -17.59f},
            {177.12f, 18.48f, -13.35f},
            {177.12f, 18.27f, -9.11f},
            {177.12f, 18.05f, -4.87f},
            {177.12f, 17.84f, -0.63f},
            {177.12f, 17.63f, 3.61f},
            {179.28f, 17.42f, 7.85f},
            {-180.00f, 17.42f, 12.09f},
            {-180.00f, 17.42f, 16.34f},
            {-180.00f, 17.42f, 20.58f},
            {-180.00f, 17.42f, 24.82f},
            {178.93f, 17.42f, 29.07f},
            {176.80f, 17.30f, 33.31f},
            {175.73f, 16.99f, 37.54f},
            {175.73f, 16.67f, 41.77f},
            {175.73f, 16.36f, 46.01f},
            {175.86f, 16.04f, 50.24f}
    };

    private static final float START_Y = 16.04f;
    private static final float START_Z = 50.24f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }
}