package frontline.combat.fcp.client.model.Aavp;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.entity.vehicle.Aavp.AAVPEntity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class AAVPModel extends VehicleModel<AAVPEntity> {

    @Override
    public ResourceLocation getModelResource(AAVPEntity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/aavp.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 13.98, -51.49]

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {-176.95f, 13.98f, -51.49f},
            {-113.79f, 11.52f, -55.12f},
            {-45.12f, 7.24f, -54.17f},
            {-27.05f, 5.10f, -50.08f},
            {-27.05f, 2.98f, -45.94f},
            {-27.05f, 0.87f, -41.79f},
            {0.00f, 0.23f, -37.27f},
            {0.00f, 0.23f, -32.62f},
            {0.00f, 0.23f, -27.97f},
            {0.00f, 0.23f, -23.32f},
            {0.00f, 0.23f, -18.67f},
            {0.00f, 0.23f, -14.02f},
            {0.00f, 0.23f, -9.38f},
            {0.00f, 0.23f, -4.73f},
            {0.00f, 0.23f, -0.08f},
            {0.00f, 0.23f, 4.57f},
            {0.00f, 0.23f, 9.22f},
            {0.00f, 0.23f, 13.87f},
            {0.00f, 0.23f, 18.52f},
            {0.00f, 0.23f, 23.17f},
            {0.00f, 0.23f, 27.82f},
            {0.00f, 0.23f, 32.47f},
            {11.88f, 0.33f, 37.12f},
            {23.45f, 2.06f, 41.42f},
            {23.45f, 3.91f, 45.69f},
            {23.45f, 5.76f, 49.95f},
            {55.59f, 8.30f, 53.74f},
            {114.14f, 12.75f, 54.16f},
            {167.80f, 15.68f, 50.77f},
            {-178.07f, 15.69f, 46.13f},
            {-177.99f, 15.52f, 41.48f},
            {-178.12f, 15.36f, 36.84f},
            {-178.19f, 15.21f, 32.19f},
            {-178.32f, 15.07f, 27.54f},
            {-178.39f, 14.94f, 22.89f},
            {-178.52f, 14.82f, 18.25f},
            {-178.66f, 14.70f, 13.60f},
            {-178.72f, 14.60f, 8.95f},
            {-178.86f, 14.50f, 4.30f},
            {-178.92f, 14.41f, -0.35f},
            {-179.06f, 14.33f, -5.00f},
            {-179.12f, 14.25f, -9.65f},
            {-179.26f, 14.19f, -14.30f},
            {-179.39f, 14.13f, -18.94f},
            {-179.46f, 14.09f, -23.59f},
            {-179.59f, 14.05f, -28.24f},
            {-179.66f, 14.02f, -32.89f},
            {-179.79f, 13.99f, -37.54f},
            {-179.86f, 13.98f, -42.19f},
            {-179.99f, 13.97f, -46.84f},
            {-176.95f, 13.98f, -51.49f}
    };

    private static final float START_Y = 13.98f;
    private static final float START_Z = -51.49f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }
}