package frontline.combat.fcp.client.model.Bmp;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.client.model.Util.WheelRotationTransforms;
import frontline.combat.fcp.entity.vehicle.Bmp.BMP1Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class BMP1Model extends VehicleModel<BMP1Entity> {

    @Override
    public ResourceLocation getModelResource(BMP1Entity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/bmp1.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<BMP1Entity> collectTransform(String boneName) {
        // Hide the Malyutka missile once it has been fired.
        if ("Malyutka".equals(boneName)) {
            return (bone, vehicle, state) -> bone.setHidden(vehicle.GetWeaponState("malyutka", 0));
        }

        return super.collectTransform(boneName);
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 20.42, 48.84]

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {176.22f, 20.42f, 48.84f},
            {128.19f, 18.55f, 52.89f},
            {78.85f, 14.27f, 54.11f},
            {33.07f, 10.55f, 51.65f},
            {32.61f, 8.08f, 47.78f},
            {32.61f, 5.60f, 43.91f},
            {32.61f, 3.12f, 40.03f},
            {2.85f, 1.37f, 35.86f},
            {0.00f, 1.37f, 31.27f},
            {0.00f, 1.37f, 26.67f},
            {0.00f, 1.37f, 22.08f},
            {0.00f, 1.37f, 17.48f},
            {0.00f, 1.37f, 12.88f},
            {0.00f, 1.37f, 8.29f},
            {0.00f, 1.37f, 3.69f},
            {0.00f, 1.37f, -0.91f},
            {0.00f, 1.37f, -5.50f},
            {0.00f, 1.37f, -10.10f},
            {0.00f, 1.37f, -14.70f},
            {0.00f, 1.37f, -19.29f},
            {0.00f, 1.37f, -23.89f},
            {0.00f, 1.37f, -28.48f},
            {-21.14f, 1.68f, -33.05f},
            {-31.59f, 3.97f, -37.02f},
            {-31.59f, 6.38f, -40.93f},
            {-31.59f, 8.79f, -44.85f},
            {-31.59f, 11.20f, -48.76f},
            {-74.57f, 14.60f, -51.67f},
            {-118.70f, 19.05f, -51.20f},
            {-167.74f, 21.74f, -47.64f},
            {178.42f, 21.81f, -43.06f},
            {178.26f, 21.67f, -38.46f},
            {178.26f, 21.53f, -33.87f},
            {178.26f, 21.39f, -29.27f},
            {179.56f, 21.26f, -24.68f},
            {-180.00f, 21.26f, -20.08f},
            {-180.00f, 21.26f, -15.49f},
            {-180.00f, 21.26f, -10.89f},
            {-180.00f, 21.26f, -6.29f},
            {-180.00f, 21.26f, -1.70f},
            {-180.00f, 21.26f, 2.90f},
            {-180.00f, 21.26f, 7.50f},
            {-180.00f, 21.26f, 12.09f},
            {-180.00f, 21.26f, 16.69f},
            {-180.00f, 21.26f, 21.28f},
            {-180.00f, 21.26f, 25.88f},
            {179.30f, 21.26f, 30.48f},
            {177.21f, 21.09f, 35.07f},
            {177.21f, 20.86f, 39.66f},
            {177.21f, 20.64f, 44.25f},
            {176.22f, 20.42f, 48.84f}
    };

    private static final float START_Y = 20.42f;
    private static final float START_Z = 48.84f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }
}