package frontline.combat.fcp.client.model.Bmp;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity;
import frontline.combat.fcp.entity.vehicle.Bmp.BMP1Entity;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class BMP1Model extends VehicleModel<BMP1Entity> {

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    // Generated by Track Builder - 56 tracks
    // Pivot: [0, 19.42, 48.84]

    private static final int TRACK_COUNT = 56;
    private static final int MAX_IDX = 56;
    private static final float[][] KEYFRAMES = {
            {177.91f, 19.42f, 48.84f},
            {128.97f, 17.72f, 52.28f},
            {75.51f, 13.97f, 53.02f},
            {25.71f, 11.18f, 50.45f},
            {25.71f, 9.46f, 46.88f},
            {25.71f, 7.74f, 43.30f},
            {25.71f, 6.02f, 39.73f},
            {12.21f, 4.33f, 36.16f},
            {0.00f, 4.29f, 32.20f},
            {0.00f, 4.29f, 28.23f},
            {0.00f, 4.29f, 24.27f},
            {0.00f, 4.29f, 20.30f},
            {0.00f, 4.29f, 16.34f},
            {0.00f, 4.29f, 12.37f},
            {0.00f, 4.29f, 8.40f},
            {0.00f, 4.29f, 4.44f},
            {0.00f, 4.29f, 0.47f},
            {0.00f, 4.29f, -3.49f},
            {0.00f, 4.29f, -7.46f},
            {0.00f, 4.29f, -11.42f},
            {0.00f, 4.29f, -15.39f},
            {0.00f, 4.29f, -19.35f},
            {0.00f, 4.29f, -23.32f},
            {0.00f, 4.29f, -27.29f},
            {-3.05f, 4.29f, -31.25f},
            {-25.59f, 5.82f, -34.87f},
            {-25.59f, 7.53f, -38.44f},
            {-25.59f, 9.25f, -42.02f},
            {-25.59f, 10.96f, -45.59f},
            {-29.55f, 12.67f, -49.17f},
            {-85.24f, 16.09f, -50.93f},
            {-138.69f, 19.65f, -49.48f},
            {177.29f, 20.79f, -45.84f},
            {174.55f, 20.38f, -41.89f},
            {175.85f, 20.05f, -37.94f},
            {179.03f, 19.88f, -33.98f},
            {-179.38f, 19.86f, -30.02f},
            {-169.01f, 19.97f, -26.05f},
            {169.01f, 19.85f, -22.21f},
            {177.92f, 19.64f, -18.25f},
            {178.75f, 19.52f, -14.28f},
            {-179.58f, 19.49f, -10.32f},
            {-178.75f, 19.54f, -6.35f},
            {-177.08f, 19.67f, -2.39f},
            {-167.64f, 19.89f, 1.57f},
            {169.04f, 19.97f, 5.42f},
            {176.67f, 19.68f, 9.37f},
            {179.04f, 19.54f, 13.34f},
            {-180.00f, 19.49f, 17.30f},
            {-179.04f, 19.53f, 21.27f},
            {-177.12f, 19.65f, 25.23f},
            {-167.60f, 19.87f, 29.19f},
            {166.53f, 19.93f, 33.03f},
            {174.20f, 19.43f, 36.96f},
            {179.19f, 19.20f, 40.92f},
            {-178.51f, 19.20f, 44.88f},
            {177.91f, 19.42f, 48.84f}
    };

    private static final float START_Y = 19.42f;
    private static final float START_Z = 48.84f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

    @Override
    public int getDefaultWrapRange(VehicleEntity vehicle) {
        return TRACK_COUNT * 2;
    }
}
