package frontline.combat.fcp.client.model.M109;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.entity.vehicle.M109.M109Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class M109Model extends VehicleModel<M109Entity> {

    @Override
    public ResourceLocation getModelResource(M109Entity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/m109.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<M109Entity> collectTransform(String boneName) {
        // Hide the Malyutka missile once it has been fired.
        if ("Malyutka".equals(boneName)) {
            return (bone, vehicle, state) -> bone.setHidden(vehicle.GetWeaponState("Malyutka", 0));
        }

        return super.collectTransform(boneName);
    }

    // Generated by Track Builder - 46 tracks
// Pivot: [0, 13.22, 51.48]

    private static final int TRACK_COUNT = 46;
    private static final int MAX_IDX = 46;
    private static final float[][] KEYFRAMES = {
            {177.14f, 13.22f, 51.48f},
            {89.88f, 10.04f, 54.66f},
            {25.98f, 6.61f, 51.56f},
            {25.98f, 4.42f, 47.07f},
            {25.98f, 2.24f, 42.58f},
            {0.00f, 1.27f, 37.79f},
            {0.00f, 1.27f, 32.80f},
            {0.00f, 1.27f, 27.81f},
            {0.00f, 1.27f, 22.82f},
            {0.00f, 1.27f, 17.83f},
            {0.00f, 1.27f, 12.84f},
            {0.00f, 1.27f, 7.85f},
            {0.00f, 1.27f, 2.85f},
            {0.00f, 1.27f, -2.14f},
            {0.00f, 1.27f, -7.13f},
            {0.00f, 1.27f, -12.12f},
            {0.00f, 1.27f, -17.11f},
            {0.00f, 1.27f, -22.10f},
            {0.00f, 1.27f, -27.09f},
            {0.00f, 1.27f, -32.08f},
            {-15.75f, 1.43f, -37.06f},
            {-19.07f, 3.05f, -41.78f},
            {-19.07f, 4.68f, -46.50f},
            {-20.54f, 6.31f, -51.21f},
            {-79.10f, 9.90f, -54.36f},
            {-138.16f, 14.46f, -52.93f},
            {179.51f, 15.69f, -48.28f},
            {176.61f, 15.40f, -43.30f},
            {176.74f, 15.11f, -38.32f},
            {177.01f, 14.84f, -33.33f},
            {177.27f, 14.59f, -28.35f},
            {177.40f, 14.36f, -23.36f},
            {177.67f, 14.15f, -18.38f},
            {177.94f, 13.95f, -13.39f},
            {178.07f, 13.78f, -8.40f},
            {178.34f, 13.63f, -3.41f},
            {178.60f, 13.49f, 1.58f},
            {178.74f, 13.37f, 6.57f},
            {179.00f, 13.28f, 11.56f},
            {179.27f, 13.20f, 16.55f},
            {179.40f, 13.15f, 21.54f},
            {179.67f, 13.11f, 26.53f},
            {179.94f, 13.09f, 31.52f},
            {-179.93f, 13.09f, 36.51f},
            {-179.66f, 13.11f, 41.50f},
            {-179.40f, 13.16f, 46.49f},
            {177.14f, 13.22f, 51.48f}
    };

    private static final float START_Y = 13.22f;
    private static final float START_Z = 51.48f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

}