package frontline.combat.fcp.client.model.M109;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.client.model.Util.CannonRecoilTransforms;
import frontline.combat.fcp.client.model.Util.ModelBoneTransforms;
import frontline.combat.fcp.client.model.Util.WheelRotationTransforms;
import frontline.combat.fcp.entity.vehicle.Lav.Lav25Entity;
import frontline.combat.fcp.entity.vehicle.M109.M109Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class M109Model extends VehicleModel<M109Entity> {

    private static final String CANNON_WEAPON = "Main";

    @Override
    public ResourceLocation getModelResource(M109Entity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/m109.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<M109Entity> collectTransform(String boneName) {

        if ("BarrelOccilator".equals(boneName)) {
            return barrelRecoil(0);
        }

        return super.collectTransform(boneName);
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 13.41, -48.84]

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {-177.02f, 13.41f, -48.84f},
            {-118.82f, 11.15f, -52.64f},
            {-55.20f, 6.74f, -52.49f},
            {-26.48f, 4.27f, -48.67f},
            {-26.48f, 2.21f, -44.53f},
            {-6.80f, 0.29f, -40.33f},
            {0.00f, 0.23f, -35.70f},
            {0.00f, 0.23f, -31.07f},
            {0.00f, 0.23f, -26.43f},
            {0.00f, 0.23f, -21.80f},
            {0.00f, 0.23f, -17.16f},
            {0.00f, 0.23f, -12.53f},
            {0.00f, 0.23f, -7.90f},
            {0.00f, 0.23f, -3.26f},
            {0.00f, 0.23f, 1.37f},
            {0.00f, 0.23f, 6.00f},
            {0.00f, 0.23f, 10.64f},
            {0.00f, 0.23f, 15.27f},
            {0.00f, 0.23f, 19.91f},
            {0.00f, 0.23f, 24.54f},
            {0.00f, 0.23f, 29.17f},
            {0.00f, 0.23f, 33.81f},
            {17.32f, 0.69f, 38.38f},
            {17.32f, 2.07f, 42.81f},
            {17.32f, 3.45f, 47.23f},
            {17.32f, 4.83f, 51.65f},
            {54.98f, 7.07f, 55.58f},
            {108.91f, 11.48f, 56.25f},
            {162.84f, 14.60f, 53.06f},
            {-178.29f, 14.71f, 48.45f},
            {-178.22f, 14.56f, 43.82f},
            {-178.36f, 14.43f, 39.19f},
            {-178.42f, 14.30f, 34.56f},
            {-178.56f, 14.17f, 29.92f},
            {-178.62f, 14.06f, 25.29f},
            {-178.76f, 13.96f, 20.66f},
            {-178.89f, 13.86f, 16.03f},
            {-178.96f, 13.77f, 11.39f},
            {-179.09f, 13.69f, 6.76f},
            {-179.16f, 13.62f, 2.13f},
            {-179.30f, 13.56f, -2.51f},
            {-179.36f, 13.51f, -7.14f},
            {-179.50f, 13.46f, -11.77f},
            {-179.63f, 13.42f, -16.41f},
            {-179.70f, 13.40f, -21.04f},
            {-179.83f, 13.38f, -25.67f},
            {-179.90f, 13.37f, -30.31f},
            {179.97f, 13.36f, -34.94f},
            {179.90f, 13.37f, -39.57f},
            {179.77f, 13.38f, -44.21f},
            {-177.02f, 13.41f, -48.84f}
    };

    private static final float START_Y = 13.41f;
    private static final float START_Z = -48.84f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {return getKeyframeValue(t, 2) - START_Z;}

    private VehicleModel.TransformContext<M109Entity> barrelRecoil(int barrelIndex) {
        return (bone, vehicle, state) -> {
            ModelBoneTransforms.clearRecoilOffsets(bone);
            if (vehicle.getCannonRecoilTime() <= 0) {
                return;
            }
            if (!CANNON_WEAPON.equals(CannonRecoilTransforms.gunnerGunName(vehicle))) {
                return;
            }
            CannonRecoilTransforms.apply(bone, vehicle, CannonRecoilTransforms.Profile.M109);
        };
    }

}