package frontline.combat.fcp.client.model.M109;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.client.model.Util.CannonRecoilTransforms;
import frontline.combat.fcp.client.model.Util.ModelBoneTransforms;
import frontline.combat.fcp.entity.vehicle.M109.M109Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class M109Model extends VehicleModel<M109Entity> {

    private static final String CANNON_WEAPON = "Main";

    @Override
    public ResourceLocation getModelResource(M109Entity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/m109.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<M109Entity> collectTransform(String boneName) {

        if (boneName.matches("wheelL\\d+")) {
            return (bone, vehicle, state) -> {
                float wheelRot = Mth.lerp(state.getPartialTick(),
                        vehicle.getLeftWheelRotO(), vehicle.getLeftWheelRot());
                bone.setRotX(-1.5f * wheelRot);
            };
        }

        if (boneName.matches("wheelR\\d+")) {
            return (bone, vehicle, state) -> {
                float wheelRot = Mth.lerp(state.getPartialTick(),
                        vehicle.getRightWheelRotO(), vehicle.getRightWheelRot());
                bone.setRotX(-1.5f * wheelRot);
            };
        }

        if ("BarrelOccilator".equals(boneName)) {
            return barrelRecoil(0);
        }

        return super.collectTransform(boneName);
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 11.40, -41.51]
// Scaled 0.85x from original [0, 13.41, -48.84] to match 0.85x model rescale (Y/Z position only, rotation untouched)

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {-177.02f, 11.40f, -41.51f},
            {-118.82f, 9.48f, -44.74f},
            {-55.20f, 5.73f, -44.62f},
            {-26.48f, 3.63f, -41.37f},
            {-26.48f, 1.88f, -37.85f},
            {-6.80f, 0.25f, -34.28f},
            {0.00f, 0.20f, -30.35f},
            {0.00f, 0.20f, -26.41f},
            {0.00f, 0.20f, -22.47f},
            {0.00f, 0.20f, -18.53f},
            {0.00f, 0.20f, -14.59f},
            {0.00f, 0.20f, -10.65f},
            {0.00f, 0.20f, -6.71f},
            {0.00f, 0.20f, -2.77f},
            {0.00f, 0.20f, 1.16f},
            {0.00f, 0.20f, 5.10f},
            {0.00f, 0.20f, 9.04f},
            {0.00f, 0.20f, 12.98f},
            {0.00f, 0.20f, 16.92f},
            {0.00f, 0.20f, 20.86f},
            {0.00f, 0.20f, 24.79f},
            {0.00f, 0.20f, 28.74f},
            {17.32f, 0.59f, 32.62f},
            {17.32f, 1.76f, 36.39f},
            {17.32f, 2.93f, 40.15f},
            {17.32f, 4.11f, 43.90f},
            {54.98f, 6.01f, 47.24f},
            {108.91f, 9.76f, 47.81f},
            {162.84f, 12.41f, 45.10f},
            {-178.29f, 12.50f, 41.18f},
            {-178.22f, 12.38f, 37.25f},
            {-178.36f, 12.27f, 33.31f},
            {-178.42f, 12.16f, 29.38f},
            {-178.56f, 12.04f, 25.43f},
            {-178.62f, 11.95f, 21.50f},
            {-178.76f, 11.87f, 17.56f},
            {-178.89f, 11.78f, 13.63f},
            {-178.96f, 11.70f, 9.68f},
            {-179.09f, 11.64f, 5.75f},
            {-179.16f, 11.58f, 1.81f},
            {-179.30f, 11.53f, -2.13f},
            {-179.36f, 11.48f, -6.07f},
            {-179.50f, 11.44f, -10.00f},
            {-179.63f, 11.41f, -13.95f},
            {-179.70f, 11.39f, -17.88f},
            {-179.83f, 11.37f, -21.82f},
            {-179.90f, 11.36f, -25.76f},
            {179.97f, 11.36f, -29.70f},
            {179.90f, 11.36f, -33.63f},
            {179.77f, 11.37f, -37.58f},
            {-177.02f, 11.40f, -41.51f}
    };

    private static final float START_Y = 11.40f;
    private static final float START_Z = -41.51f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {return getKeyframeValue(t, 2) - START_Z;}

    private VehicleModel.TransformContext<M109Entity> barrelRecoil(int barrelIndex) {
        return (bone, vehicle, state) -> {
            ModelBoneTransforms.clearRecoilOffsets(bone);
            if (vehicle.getCannonRecoilTime() <= 0) {
                return;
            }
            if (!CANNON_WEAPON.equals(CannonRecoilTransforms.gunnerGunName(vehicle))) {
                return;
            }
            CannonRecoilTransforms.apply(bone, vehicle, CannonRecoilTransforms.Profile.M109);
        };
    }

}