package frontline.combat.fcp.client.model.Msta;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.client.model.Util.CannonRecoilTransforms;
import frontline.combat.fcp.client.model.Util.ModelBoneTransforms;
import frontline.combat.fcp.entity.vehicle.M109.M109Entity;
import frontline.combat.fcp.entity.vehicle.Msta.MstaEntity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class MstaModel extends VehicleModel<MstaEntity> {

    private static final String CANNON_WEAPON = "Main";

    @Override
    public ResourceLocation getModelResource(MstaEntity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/msta.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<MstaEntity> collectTransform(String boneName) {

        if ("BarrelOccilator".equals(boneName)) {
            return barrelRecoil(0);
        }

        return super.collectTransform(boneName);
    }

    private VehicleModel.TransformContext<MstaEntity> barrelRecoil(int barrelIndex) {
        return (bone, vehicle, state) -> {
            ModelBoneTransforms.clearRecoilOffsets(bone);
            if (vehicle.getCannonRecoilTime() <= 0) {
                return;
            }
            if (!CANNON_WEAPON.equals(CannonRecoilTransforms.gunnerGunName(vehicle))) {
                return;
            }
            CannonRecoilTransforms.apply(bone, vehicle, CannonRecoilTransforms.Profile.MSTA);
        };
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 18.85, 56.56]

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {176.83f, 18.85f, 56.56f},
            {127.69f, 16.59f, 60.99f},
            {72.89f, 11.68f, 61.77f},
            {33.30f, 8.00f, 58.35f},
            {33.30f, 5.17f, 54.04f},
            {33.30f, 2.33f, 49.73f},
            {2.73f, 0.25f, 45.10f},
            {0.00f, 0.24f, 39.94f},
            {0.00f, 0.24f, 34.78f},
            {0.00f, 0.24f, 29.63f},
            {0.00f, 0.24f, 24.47f},
            {0.00f, 0.24f, 19.31f},
            {0.00f, 0.24f, 14.15f},
            {0.00f, 0.24f, 9.00f},
            {0.00f, 0.24f, 3.84f},
            {0.00f, 0.24f, -1.32f},
            {0.00f, 0.24f, -6.48f},
            {0.00f, 0.24f, -11.63f},
            {0.00f, 0.24f, -16.79f},
            {0.00f, 0.24f, -21.95f},
            {0.00f, 0.24f, -27.11f},
            {0.00f, 0.24f, -32.26f},
            {0.00f, 0.24f, -37.42f},
            {-36.13f, 1.42f, -42.32f},
            {-37.69f, 4.58f, -46.40f},
            {-37.69f, 7.73f, -50.48f},
            {-37.69f, 10.88f, -54.56f},
            {-75.27f, 14.80f, -57.71f},
            {-133.72f, 19.57f, -56.42f},
            {-179.56f, 21.17f, -51.72f},
            {177.84f, 20.99f, -46.56f},
            {177.90f, 20.80f, -41.41f},
            {178.01f, 20.61f, -36.26f},
            {178.13f, 20.44f, -31.10f},
            {178.24f, 20.27f, -25.95f},
            {178.30f, 20.12f, -20.79f},
            {178.41f, 19.97f, -15.64f},
            {178.52f, 19.83f, -10.48f},
            {178.64f, 19.70f, -5.32f},
            {178.70f, 19.58f, -0.17f},
            {178.81f, 19.47f, 4.99f},
            {178.92f, 19.37f, 10.15f},
            {179.04f, 19.27f, 15.30f},
            {179.09f, 19.19f, 20.46f},
            {179.21f, 19.11f, 25.62f},
            {179.32f, 19.05f, 30.77f},
            {179.43f, 18.99f, 35.93f},
            {179.49f, 18.94f, 41.09f},
            {179.60f, 18.90f, 46.24f},
            {179.72f, 18.87f, 51.40f},
            {176.83f, 18.85f, 56.56f}
    };

    private static final float START_Y = 18.85f;
    private static final float START_Z = 56.56f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

}
