package frontline.combat.fcp.client.model.Msta;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import frontline.combat.fcp.FCP;
import frontline.combat.fcp.client.model.Util.CannonRecoilTransforms;
import frontline.combat.fcp.client.model.Util.ModelBoneTransforms;
import frontline.combat.fcp.entity.vehicle.M109.M109Entity;
import frontline.combat.fcp.entity.vehicle.Msta.MstaEntity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;

public class MstaModel extends VehicleModel<MstaEntity> {

    private static final String CANNON_WEAPON = "Main";

    @Override
    public ResourceLocation getModelResource(MstaEntity animatable) {
        return new ResourceLocation(FCP.MODID, "geo/msta.geo.json");
    }

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return false;
    }

    @Override
    public @Nullable VehicleModel.TransformContext<MstaEntity> collectTransform(String boneName) {

        if ("BarrelOccilator".equals(boneName)) {
            return barrelRecoil(0);
        }

        return super.collectTransform(boneName);
    }

    private VehicleModel.TransformContext<MstaEntity> barrelRecoil(int barrelIndex) {
        return (bone, vehicle, state) -> {
            ModelBoneTransforms.clearRecoilOffsets(bone);
            if (vehicle.getCannonRecoilTime() <= 0) {
                return;
            }
            if (!CANNON_WEAPON.equals(CannonRecoilTransforms.gunnerGunName(vehicle))) {
                return;
            }
            CannonRecoilTransforms.apply(bone, vehicle, CannonRecoilTransforms.Profile.MSTA);
        };
    }

    // Generated by Track Builder - 50 tracks
// Pivot: [0, 16.02, 48.08]
// Scaled 0.85x from original [0, 18.85, 56.56] to match 0.85x model rescale (Y/Z position only, rotation untouched)

    private static final int TRACK_COUNT = 50;
    private static final int MAX_IDX = 50;
    private static final float[][] KEYFRAMES = {
            {176.83f, 16.02f, 48.08f},
            {127.69f, 14.10f, 51.84f},
            {72.89f, 9.93f, 52.50f},
            {33.30f, 6.80f, 49.60f},
            {33.30f, 4.39f, 45.93f},
            {33.30f, 1.98f, 42.27f},
            {2.73f, 0.21f, 38.34f},
            {0.00f, 0.20f, 33.95f},
            {0.00f, 0.20f, 29.56f},
            {0.00f, 0.20f, 25.19f},
            {0.00f, 0.20f, 20.80f},
            {0.00f, 0.20f, 16.41f},
            {0.00f, 0.20f, 12.03f},
            {0.00f, 0.20f, 7.65f},
            {0.00f, 0.20f, 3.26f},
            {0.00f, 0.20f, -1.12f},
            {0.00f, 0.20f, -5.51f},
            {0.00f, 0.20f, -9.89f},
            {0.00f, 0.20f, -14.27f},
            {0.00f, 0.20f, -18.66f},
            {0.00f, 0.20f, -23.04f},
            {0.00f, 0.20f, -27.42f},
            {0.00f, 0.20f, -31.81f},
            {-36.13f, 1.21f, -35.97f},
            {-37.69f, 3.89f, -39.44f},
            {-37.69f, 6.57f, -42.91f},
            {-37.69f, 9.25f, -46.38f},
            {-75.27f, 12.58f, -49.05f},
            {-133.72f, 16.63f, -47.96f},
            {-179.56f, 17.99f, -43.96f},
            {177.84f, 17.84f, -39.58f},
            {177.90f, 17.68f, -35.20f},
            {178.01f, 17.52f, -30.82f},
            {178.13f, 17.37f, -26.44f},
            {178.24f, 17.23f, -22.06f},
            {178.30f, 17.10f, -17.67f},
            {178.41f, 16.97f, -13.29f},
            {178.52f, 16.86f, -8.91f},
            {178.64f, 16.74f, -4.52f},
            {178.70f, 16.64f, -0.14f},
            {178.81f, 16.55f, 4.24f},
            {178.92f, 16.46f, 8.63f},
            {179.04f, 16.38f, 13.01f},
            {179.09f, 16.31f, 17.39f},
            {179.21f, 16.24f, 21.78f},
            {179.32f, 16.19f, 26.15f},
            {179.43f, 16.14f, 30.54f},
            {179.49f, 16.10f, 34.93f},
            {179.60f, 16.06f, 39.30f},
            {179.72f, 16.04f, 43.69f},
            {176.83f, 16.02f, 48.08f}
    };

    private static final float START_Y = 16.02f;
    private static final float START_Z = 48.08f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

}