package frontline.combat.fcp.client.model.Abrams;

import frontline.combat.fcp.client.model.Util.FCPTrackPath;

/**
 * Shared track paths for the M1a1 hull. Every variant on this hull uses the same geo, so they all
 * share one table here instead of each model carrying a copy that can drift out of step with the others.
 * <p>
 * 77 links at a track distance of 100/77 fill the entity's track animation length of 100.
 * Bone pivot: Blockbench [-29.17, 23.76, 64.29] for every trackMov/trackRot bone (mirror X for the other side).
 * The geo must have trackMov/trackRot bone pairs 0..76 per side, or only the bones that exist will animate.
 * <p>
 * To flip one variant, return a view in that model's getTrackPath():
 * {@code M1A1.reversed()}, {@code M1A1.rotationInverted()} or {@code M1A1.rotationOffset(180)}.
 * <p>
 * Path length 308.56 px, segment length 4.007 px.
 * Vehicle JSON "TrackRotSpeed" for no-slip: 1.651
 * <p>
 * Generated by the SBW Track Builder Blockbench plugin.
 */
public final class M1a1TrackPaths {

    private static final int TRACK_COUNT = 77;
    private static final int ANIMATION_LENGTH = 100; // entity getTrackAnimationLength()

    /** {rotX, y, z} keyframes - 1 per link, plus a closing row. */
    private static final float[][] M1A1_KEYFRAMES = {
            {-3.30f, 23.76f, 64.29f},
            {1.96f, 23.61f, 60.28f},
            {1.85f, 23.48f, 56.28f},
            {1.75f, 23.36f, 52.27f},
            {1.64f, 23.24f, 48.26f},
            {1.54f, 23.13f, 44.26f},
            {1.43f, 23.02f, 40.25f},
            {1.32f, 22.93f, 36.25f},
            {1.22f, 22.84f, 32.24f},
            {1.11f, 22.76f, 28.23f},
            {1.01f, 22.68f, 24.23f},
            {0.90f, 22.61f, 20.22f},
            {0.80f, 22.56f, 16.21f},
            {0.69f, 22.50f, 12.21f},
            {0.59f, 22.46f, 8.20f},
            {0.48f, 22.42f, 4.19f},
            {0.37f, 22.39f, 0.19f},
            {0.27f, 22.37f, -3.82f},
            {0.16f, 22.35f, -7.83f},
            {0.06f, 22.35f, -11.84f},
            {-0.05f, 22.35f, -15.84f},
            {-0.15f, 22.35f, -19.85f},
            {-0.26f, 22.37f, -23.86f},
            {-0.37f, 22.39f, -27.86f},
            {-0.47f, 22.42f, -31.87f},
            {-0.58f, 22.46f, -35.88f},
            {-0.68f, 22.50f, -39.89f},
            {-0.79f, 22.55f, -43.89f},
            {-0.89f, 22.61f, -47.90f},
            {-1.00f, 22.68f, -51.91f},
            {-1.11f, 22.75f, -55.91f},
            {-1.21f, 22.83f, -59.92f},
            {-1.32f, 22.92f, -63.92f},
            {5.94f, 22.99f, -67.93f},
            {39.04f, 21.55f, -71.60f},
            {74.35f, 18.26f, -73.77f},
            {109.66f, 14.32f, -73.63f},
            {144.62f, 11.18f, -71.24f},
            {157.60f, 9.51f, -67.60f},
            {157.60f, 7.99f, -63.90f},
            {157.60f, 6.46f, -60.19f},
            {157.60f, 4.93f, -56.49f},
            {157.60f, 3.40f, -52.78f},
            {164.91f, 1.90f, -49.07f},
            {180.00f, 1.61f, -45.09f},
            {180.00f, 1.61f, -41.09f},
            {180.00f, 1.61f, -37.08f},
            {180.00f, 1.61f, -33.07f},
            {180.00f, 1.61f, -29.06f},
            {180.00f, 1.61f, -25.06f},
            {180.00f, 1.61f, -21.05f},
            {180.00f, 1.61f, -17.04f},
            {180.00f, 1.61f, -13.03f},
            {180.00f, 1.61f, -9.03f},
            {180.00f, 1.61f, -5.02f},
            {180.00f, 1.61f, -1.01f},
            {180.00f, 1.61f, 2.99f},
            {180.00f, 1.61f, 7.00f},
            {180.00f, 1.61f, 11.01f},
            {180.00f, 1.61f, 15.02f},
            {180.00f, 1.61f, 19.02f},
            {180.00f, 1.61f, 23.03f},
            {180.00f, 1.61f, 27.04f},
            {180.00f, 1.61f, 31.04f},
            {180.00f, 1.61f, 35.05f},
            {180.00f, 1.61f, 39.06f},
            {180.00f, 1.61f, 43.07f},
            {181.67f, 1.61f, 47.07f},
            {204.25f, 2.39f, 50.95f},
            {209.07f, 4.33f, 54.45f},
            {209.07f, 6.28f, 57.96f},
            {209.07f, 8.23f, 61.46f},
            {209.07f, 10.17f, 64.96f},
            {219.91f, 12.20f, 68.41f},
            {254.28f, 15.50f, 70.58f},
            {289.67f, 19.44f, 70.44f},
            {325.03f, 22.58f, 68.05f},
            {356.70f, 23.76f, 64.29f}
    };

    public static final FCPTrackPath M1A1 = new FCPTrackPath(TRACK_COUNT, ANIMATION_LENGTH, M1A1_KEYFRAMES);

    private M1a1TrackPaths() {
    }
}
